import { GoogleGenAI } from "@google/genai";

const getAiClient = () => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) throw new Error("API Key not found");
  return new GoogleGenAI({ apiKey });
};

export const editImageWithGemini = async (
  base64Image: string,
  prompt: string,
  mimeType: string = 'image/png'
): Promise<string> => {
  try {
    const ai = getAiClient();
    
    // Using gemini-2.5-flash-image for image editing/variation tasks
    const modelId = 'gemini-2.5-flash-image';

    // Clean base64 string if it contains metadata header
    const cleanBase64 = base64Image.replace(/^data:image\/(png|jpeg|webp);base64,/, "");

    const response = await ai.models.generateContent({
      model: modelId,
      contents: {
        parts: [
          {
            inlineData: {
              data: cleanBase64,
              mimeType: mimeType
            }
          },
          {
            text: prompt + " Return the result as a generated image."
          }
        ]
      }
    });

    // Check for inline data (image) in response
    // Iterate through parts to find the image
    const parts = response.candidates?.[0]?.content?.parts;
    if (parts) {
        for (const part of parts) {
            if (part.inlineData && part.inlineData.data) {
                return `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
            }
        }
    }
    
    throw new Error("No image generated by Gemini. Try a different prompt.");

  } catch (error: any) {
    console.error("Gemini API Error:", error);
    throw new Error(error.message || "Failed to process image with AI");
  }
};

export const analyzeImageSuggestions = async (base64Image: string): Promise<string> => {
    try {
        const ai = getAiClient();
        const cleanBase64 = base64Image.replace(/^data:image\/(png|jpeg|webp);base64,/, "");

        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: {
                parts: [
                    { inlineData: { data: cleanBase64, mimeType: 'image/jpeg' } },
                    { text: "Analyze this image and suggest 3 short, creative edit prompts I could use to transform it (e.g., 'Make it look like a pencil sketch'). Return ONLY the 3 prompts separated by pipes |." }
                ]
            }
        });

        return response.text || "Make it watercolor|Cyberpunk style|Vintage film look";
    } catch (e) {
        return "Make it watercolor|Cyberpunk style|Vintage film look";
    }
}
